version: '3.7'
services:
  mypostgres:
    image: postgres
    container_name: mypostgress
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "251210Nms."
      POSTGRES_DB: "ticketing-app"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - mypostgres
networks:
  webnet:
    driver: bridge
volumes:
  initdb:
